### PR TITLE
Set GitHubAPIURL when set

### LINKED ISSUE #3: Support for Github Enterprise?!
I'm trying to apply this resource to our inhouse concourse + Github Enterprise setup. Unfortunately I got an errror (see below). Interresting part here is that it tries to connect to `https://api.github.com` even so  `github_api_url` parameter is set to our inhouse installation. What I could not read in code is, if it's actually used?

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
getting deployments list
[31merror running command: GET https://api.github.com/repos/digital-banking/solaris-logging-ruby/deployments: 401 Bad credentials []
[0mgoroutine 1 [running]:
runtime/debug.Stack(0x16, 0xc420045d98, 0x2)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/ahume/github-deployment-resource.Fatal(0x6c3200, 0xf, 0x7d7bc0, 0xc42019e0a0)
	/go/src/github.com/ahume/github-deployment-resource/fmt.go:13 +0x120
main.main()
	/go/src/github.com/ahume/github-deployment-resource/cmd/check/check.go:22 +0x28d
```

Thanks, Tobi

### PR DESCRIPTION
**Pull request by rngtng**
Somehow this was never implemented? Pls advice what's best to test this.

fixes #3

### CODE REVIEW

**Comment by rngtng** [comment]
btw. is there a working docker setup or similar? I couldn't get the `scripts/xxx` runnning :(

**Comment by rngtng** [comment]
@ahume any progress on this

**Comment by ahume** [comment]
@rngtng Thanks for reporting the issue, sorry for the delay responding.

I have also raised PR #16 for this. It's slightly different to your fix, I think because I also recently updated the `go-github` package we were using.

If you want to rebase and update your PR to fix, I will happily merge and you can get the author credit. If not, I will just merge mine in the next few days. Thanks.

**Comment by rngtng** [comment]
@ahume thanks for responding. No worries not hunting credits, just take yours #16 thx

**Pull request closed without merging**
